# docker run --name fiscalblog --volume="$PWD:/srv/jekyll" -p 3000:4000 -it jekyll/jekyll:$JEKYLL_VERSION jekyll serve

version: '3'
services:
  jekyll-serve:
    image: jekyll/jekyll:4.0
    volumes:
      - '.:/srv/jekyll'
    ports:
      - 3000:4000
    command: 'jekyll serve'